# Generated by Django 3.0.5 on 2020-05-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truecaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=15)),
                ('access_token', models.CharField(max_length=80)),
                ('requestId', models.CharField(max_length=80)),
            ],
        ),
    ]
